// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "ui.h"

int samp_start=0;

void dark_mode_on(lv_event_t *e)
{
    lv_color_t bg_color_white = lv_color_hex(0x111111);
    lv_color_t bg_color_black = lv_color_hex(0xFFFFFF);

    lv_obj_add_state(ui_Dark_Mode_Switch, LV_STATE_CHECKED);
    lv_obj_add_state(ui_Dark_Mode_Switch_Sett, LV_STATE_CHECKED);

    lv_obj_set_style_text_color(ui_Dark_Mode_Label, bg_color_black, 0);
    lv_obj_set_style_text_color(ui_Dark_Mode_Label_Sett, bg_color_black, 0);
    lv_obj_set_style_bg_color(ui_Home_Scr, bg_color_white, 0);
    lv_obj_set_style_bg_color(ui_Color_Scr, bg_color_white, 0);
    lv_obj_set_style_bg_color(ui_InfoScr, bg_color_white, 0);

    lv_obj_set_style_bg_color(ui_Settings_scroll_panel, bg_color_white, 0);
    lv_obj_set_style_border_color(ui_Settings_scroll_panel, bg_color_white, 0);
}

void dark_mode_off(lv_event_t *e)
{
    lv_color_t bg_color_white = lv_color_hex(0x111111);
    lv_color_t bg_color_black = lv_color_hex(0xFFFFFF);

    lv_obj_clear_state(ui_Dark_Mode_Switch, LV_STATE_CHECKED);
    lv_obj_clear_state(ui_Dark_Mode_Switch_Sett, LV_STATE_CHECKED);

    lv_obj_set_style_text_color(ui_Dark_Mode_Label, bg_color_white, 0);
    lv_obj_set_style_text_color(ui_Dark_Mode_Label_Sett, bg_color_white, 0);
    lv_obj_set_style_bg_color(ui_Home_Scr, bg_color_black, 0);
    lv_obj_set_style_bg_color(ui_Color_Scr, bg_color_black, 0);
    lv_obj_set_style_bg_color(ui_InfoScr, bg_color_black, 0);

    lv_obj_set_style_bg_color(ui_Settings_scroll_panel, bg_color_black, 0);
    lv_obj_set_style_border_color(ui_Settings_scroll_panel, bg_color_black, 0);
}

int color_start=0;

void ColorGame(lv_event_t * e)
{
	color_start=1;
}

static int freq_arr[3]={200,400,440};
int curr_freq=1;
int song_start=0;
extern lv_obj_t * ui_imepj;

void startMusic(lv_event_t * e)
{
	song_start=1;
}

void changePrevSong(lv_event_t * e)
{
	curr_freq=(curr_freq+2)%3;
    lv_label_set_text_fmt(ui_imepj, "signal %d Hz", freq_arr[curr_freq]);
}

void changeNextSong(lv_event_t * e)
{
	curr_freq=(curr_freq+1)%3;
    lv_label_set_text_fmt(ui_imepj, "signal %d Hz", freq_arr[curr_freq]);
}

void stopMusic(lv_event_t * e)
{
	song_start=0;
}

void pulseMeterStart(lv_event_t * e)
{
    if (samp_start == 0) {
        lv_label_set_text(ui_Label9, "stop");
        samp_start=1;
        
    }
    else{
        lv_label_set_text(ui_Label9, "play");
        samp_start=0;
    }
}

void takePhoto(lv_event_t * e)
{
	// Your code here
}
