// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_Color_Scr = NULL;
lv_obj_t * ui_BL_logo_Color = NULL;
lv_obj_t * ui_LED_color_panel = NULL;
lv_obj_t * ui_LED_color_label = NULL;
lv_obj_t * ui_resultColor = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Playbtng3 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Home_Btn_Sett2 = NULL;
lv_obj_t * ui_Home_Img_S2 = NULL;
lv_obj_t * ui_Label21 = NULL;
// event funtions
void ui_event_Playbtng3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ColorGame(e);
    }
}

void ui_event_Home_Btn_Sett2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home_Scr, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Home_Scr_screen_init);
    }
}

// build funtions

void ui_Color_Scr_screen_init(void)
{
    ui_Color_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Color_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color_Scr, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BL_logo_Color = lv_img_create(ui_Color_Scr);
    lv_img_set_src(ui_BL_logo_Color, &ui_img_bl_logo_symbol_png);
    lv_obj_set_width(ui_BL_logo_Color, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BL_logo_Color, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BL_logo_Color, 139);
    lv_obj_set_y(ui_BL_logo_Color, -101);
    lv_obj_set_align(ui_BL_logo_Color, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BL_logo_Color, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BL_logo_Color, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BL_logo_Color, 50);

    ui_LED_color_panel = lv_obj_create(ui_Color_Scr);
    lv_obj_set_width(ui_LED_color_panel, 139);
    lv_obj_set_height(ui_LED_color_panel, 31);
    lv_obj_set_x(ui_LED_color_panel, -76);
    lv_obj_set_y(ui_LED_color_panel, 7);
    lv_obj_set_align(ui_LED_color_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LED_color_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LED_color_panel, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LED_color_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LED_color_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LED_color_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LED_color_label = lv_label_create(ui_LED_color_panel);
    lv_obj_set_width(ui_LED_color_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LED_color_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LED_color_label, 2);
    lv_obj_set_y(ui_LED_color_label, 1);
    lv_obj_set_align(ui_LED_color_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LED_color_label, "LED color");
    lv_obj_set_style_text_font(ui_LED_color_label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resultColor = lv_obj_create(ui_Color_Scr);
    lv_obj_set_width(ui_resultColor, 100);
    lv_obj_set_height(ui_resultColor, 50);
    lv_obj_set_x(ui_resultColor, 85);
    lv_obj_set_y(ui_resultColor, 4);
    lv_obj_set_align(ui_resultColor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_resultColor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_resultColor, lv_color_hex(0xFB151A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_resultColor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_resultColor);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);

    ui_Playbtng3 = lv_btn_create(ui_Color_Scr);
    lv_obj_set_width(ui_Playbtng3, 75);
    lv_obj_set_height(ui_Playbtng3, 68);
    lv_obj_set_y(ui_Playbtng3, -68);
    lv_obj_set_x(ui_Playbtng3, lv_pct(-25));
    lv_obj_set_align(ui_Playbtng3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Playbtng3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Playbtng3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Playbtng3, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Playbtng3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Playbtng3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "play");

    ui_Home_Btn_Sett2 = lv_btn_create(ui_Color_Scr);
    lv_obj_set_width(ui_Home_Btn_Sett2, 36);
    lv_obj_set_height(ui_Home_Btn_Sett2, 31);
    lv_obj_set_x(ui_Home_Btn_Sett2, -133);
    lv_obj_set_y(ui_Home_Btn_Sett2, 94);
    lv_obj_set_align(ui_Home_Btn_Sett2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Btn_Sett2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_Btn_Sett2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Btn_Sett2, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Btn_Sett2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Img_S2 = lv_img_create(ui_Home_Btn_Sett2);
    lv_img_set_src(ui_Home_Img_S2, &ui_img_home_icon_png);
    lv_obj_set_width(ui_Home_Img_S2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Img_S2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_Img_S2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Img_S2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home_Img_S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Home_Img_S2, 50);

    ui_Label21 = lv_label_create(ui_Color_Scr);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 44);
    lv_obj_set_y(ui_Label21, -82);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Bojotragac");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x342EFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label21, lv_color_hex(0xF113F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Label21, lv_color_hex(0xB9AF0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Label21, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label21, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Label21, lv_color_hex(0x54C4E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Label21, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Label21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Playbtng3, ui_event_Playbtng3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home_Btn_Sett2, ui_event_Home_Btn_Sett2, LV_EVENT_ALL, NULL);

}

void ui_Color_Scr_screen_destroy(void)
{
    if(ui_Color_Scr) lv_obj_del(ui_Color_Scr);

    // NULL screen variables
    ui_Color_Scr = NULL;
    ui_BL_logo_Color = NULL;
    ui_LED_color_panel = NULL;
    ui_LED_color_label = NULL;
    ui_resultColor = NULL;
    ui_Label3 = NULL;
    ui_Playbtng3 = NULL;
    ui_Label14 = NULL;
    ui_Home_Btn_Sett2 = NULL;
    ui_Home_Img_S2 = NULL;
    ui_Label21 = NULL;

}
