// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_GAMESCR_H
#define UI_GAMESCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Gamescr
extern void ui_Gamescr_screen_init(void);
extern void ui_Gamescr_screen_destroy(void);
extern lv_obj_t * ui_Gamescr;
extern void ui_event_Color_Btn_Home2(lv_event_t * e);
extern lv_obj_t * ui_Color_Btn_Home2;
extern lv_obj_t * ui_Colorwheel_Home2;
extern void ui_event_Home_Btn_Sett3(lv_event_t * e);
extern lv_obj_t * ui_Home_Btn_Sett3;
extern lv_obj_t * ui_Home_Img_S3;
extern void ui_event_PeekBooBTN(lv_event_t * e);
extern lv_obj_t * ui_PeekBooBTN;
extern lv_obj_t * ui_Label4;
extern void ui_event_TetriBtn(lv_event_t * e);
extern lv_obj_t * ui_TetriBtn;
extern lv_obj_t * ui_Label1;
extern void ui_event_SnakeBtn(lv_event_t * e);
extern lv_obj_t * ui_SnakeBtn;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

