// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_GLAZBASCR_H
#define UI_GLAZBASCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_glazbascr
extern void ui_glazbascr_screen_init(void);
extern void ui_glazbascr_screen_destroy(void);
extern lv_obj_t * ui_glazbascr;
extern void ui_event_Playbtng(lv_event_t * e);
extern lv_obj_t * ui_Playbtng;
extern lv_obj_t * ui_Label10;
extern void ui_event_prevbtn(lv_event_t * e);
extern lv_obj_t * ui_prevbtn;
extern lv_obj_t * ui_Label11;
extern void ui_event_nextbtn(lv_event_t * e);
extern lv_obj_t * ui_nextbtn;
extern lv_obj_t * ui_Label12;
extern void ui_event_pausebtn(lv_event_t * e);
extern lv_obj_t * ui_pausebtn;
extern lv_obj_t * ui_Label13;
extern void ui_event_Home_Btn_Sett4(lv_event_t * e);
extern lv_obj_t * ui_Home_Btn_Sett4;
extern lv_obj_t * ui_Home_Img_S4;
extern lv_obj_t * ui_Panelpj;
extern lv_obj_t * ui_imepj;
extern lv_obj_t * ui_Label20;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

