// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_glazbascr = NULL;
lv_obj_t * ui_Playbtng = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_prevbtn = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_nextbtn = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_pausebtn = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Home_Btn_Sett4 = NULL;
lv_obj_t * ui_Home_Img_S4 = NULL;
lv_obj_t * ui_Panelpj = NULL;
lv_obj_t * ui_imepj = NULL;
// event funtions
void ui_event_Playbtng(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        startMusic(e);
    }
}

void ui_event_prevbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        changePrevSong(e);
    }
}

void ui_event_nextbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        changeNextSong(e);
    }
}

void ui_event_pausebtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        stopMusic(e);
    }
}

void ui_event_Home_Btn_Sett4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home_Scr, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Home_Scr_screen_init);
    }
}

// build funtions

void ui_glazbascr_screen_init(void)
{
    ui_glazbascr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_glazbascr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_glazbascr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_glazbascr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Playbtng = lv_btn_create(ui_glazbascr);
    lv_obj_set_width(ui_Playbtng, 75);
    lv_obj_set_height(ui_Playbtng, 68);
    lv_obj_set_y(ui_Playbtng, -68);
    lv_obj_set_x(ui_Playbtng, lv_pct(-25));
    lv_obj_set_align(ui_Playbtng, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Playbtng, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Playbtng, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Playbtng, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Playbtng, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Playbtng);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "play\n");

    ui_prevbtn = lv_btn_create(ui_glazbascr);
    lv_obj_set_width(ui_prevbtn, 75);
    lv_obj_set_height(ui_prevbtn, 68);
    lv_obj_set_y(ui_prevbtn, 28);
    lv_obj_set_x(ui_prevbtn, lv_pct(-26));
    lv_obj_set_align(ui_prevbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_prevbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_prevbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_prevbtn, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_prevbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_prevbtn);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "prev");

    ui_nextbtn = lv_btn_create(ui_glazbascr);
    lv_obj_set_width(ui_nextbtn, 75);
    lv_obj_set_height(ui_nextbtn, 68);
    lv_obj_set_y(ui_nextbtn, 25);
    lv_obj_set_x(ui_nextbtn, lv_pct(30));
    lv_obj_set_align(ui_nextbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nextbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_nextbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_nextbtn, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nextbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_nextbtn);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "next");

    ui_pausebtn = lv_btn_create(ui_glazbascr);
    lv_obj_set_width(ui_pausebtn, 75);
    lv_obj_set_height(ui_pausebtn, 68);
    lv_obj_set_y(ui_pausebtn, 26);
    lv_obj_set_x(ui_pausebtn, lv_pct(3));
    lv_obj_set_align(ui_pausebtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pausebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pausebtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pausebtn, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pausebtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_pausebtn);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "pause");

    ui_Home_Btn_Sett4 = lv_btn_create(ui_glazbascr);
    lv_obj_set_width(ui_Home_Btn_Sett4, 36);
    lv_obj_set_height(ui_Home_Btn_Sett4, 31);
    lv_obj_set_x(ui_Home_Btn_Sett4, -133);
    lv_obj_set_y(ui_Home_Btn_Sett4, 94);
    lv_obj_set_align(ui_Home_Btn_Sett4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Btn_Sett4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_Btn_Sett4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Btn_Sett4, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Btn_Sett4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Img_S4 = lv_img_create(ui_Home_Btn_Sett4);
    lv_img_set_src(ui_Home_Img_S4, &ui_img_home_icon_png);
    lv_obj_set_width(ui_Home_Img_S4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Img_S4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_Img_S4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Img_S4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home_Img_S4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Home_Img_S4, 50);

    ui_Panelpj = lv_obj_create(ui_glazbascr);
    lv_obj_set_width(ui_Panelpj, 139);
    lv_obj_set_height(ui_Panelpj, 50);
    lv_obj_set_x(ui_Panelpj, 57);
    lv_obj_set_y(ui_Panelpj, -67);
    lv_obj_set_align(ui_Panelpj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelpj, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imepj = lv_label_create(ui_Panelpj);
    lv_obj_set_width(ui_imepj, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imepj, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imepj, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Playbtng, ui_event_Playbtng, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_prevbtn, ui_event_prevbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_nextbtn, ui_event_nextbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pausebtn, ui_event_pausebtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home_Btn_Sett4, ui_event_Home_Btn_Sett4, LV_EVENT_ALL, NULL);

}

void ui_glazbascr_screen_destroy(void)
{
    if(ui_glazbascr) lv_obj_del(ui_glazbascr);

    // NULL screen variables
    ui_glazbascr = NULL;
    ui_Playbtng = NULL;
    ui_Label10 = NULL;
    ui_prevbtn = NULL;
    ui_Label11 = NULL;
    ui_nextbtn = NULL;
    ui_Label12 = NULL;
    ui_pausebtn = NULL;
    ui_Label13 = NULL;
    ui_Home_Btn_Sett4 = NULL;
    ui_Home_Img_S4 = NULL;
    ui_Panelpj = NULL;
    ui_imepj = NULL;

}
