// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_Gamescr = NULL;
lv_obj_t * ui_Color_Btn_Home2 = NULL;
lv_obj_t * ui_Colorwheel_Home2 = NULL;
lv_obj_t * ui_Home_Btn_Sett3 = NULL;
lv_obj_t * ui_Home_Img_S3 = NULL;
lv_obj_t * ui_PeekBooBTN = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_TetriBtn = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_SnakeBtn = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_Color_Btn_Home2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LargeBtn_Animation(ui_Photo_Btn, 0);
        MoveColorToCenter_Animation(ui_Photo_Btn, 0);
        HideBtn_Animation(ui_wifi_Btn, 0);
        ShowBtn_Animation(ui_wifi_Btn, 1200);
    }
}

void ui_event_Home_Btn_Sett3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home_Scr, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Home_Scr_screen_init);
    }
}

void ui_event_PeekBooBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PeekBooScr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_PeekBooScr_screen_init);
    }
}

void ui_event_TetriBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PeekBooScr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_PeekBooScr_screen_init);
    }
}

void ui_event_SnakeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PeekBooScr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_PeekBooScr_screen_init);
    }
}

// build funtions

void ui_Gamescr_screen_init(void)
{
    ui_Gamescr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Gamescr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Gamescr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gamescr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Color_Btn_Home2 = lv_btn_create(ui_Gamescr);
    lv_obj_set_width(ui_Color_Btn_Home2, 75);
    lv_obj_set_height(ui_Color_Btn_Home2, 68);
    lv_obj_set_x(ui_Color_Btn_Home2, -83);
    lv_obj_set_y(ui_Color_Btn_Home2, -59);
    lv_obj_set_align(ui_Color_Btn_Home2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Color_Btn_Home2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Color_Btn_Home2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color_Btn_Home2, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color_Btn_Home2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colorwheel_Home2 = lv_img_create(ui_Color_Btn_Home2);
    lv_img_set_src(ui_Colorwheel_Home2, &ui_img_colorwheel_icon_png);
    lv_obj_set_width(ui_Colorwheel_Home2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Colorwheel_Home2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Colorwheel_Home2, -1);
    lv_obj_set_y(ui_Colorwheel_Home2, -2);
    lv_obj_set_align(ui_Colorwheel_Home2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Colorwheel_Home2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Colorwheel_Home2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Colorwheel_Home2, 120);

    ui_Home_Btn_Sett3 = lv_btn_create(ui_Gamescr);
    lv_obj_set_width(ui_Home_Btn_Sett3, 36);
    lv_obj_set_height(ui_Home_Btn_Sett3, 31);
    lv_obj_set_x(ui_Home_Btn_Sett3, -133);
    lv_obj_set_y(ui_Home_Btn_Sett3, 94);
    lv_obj_set_align(ui_Home_Btn_Sett3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Btn_Sett3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_Btn_Sett3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Btn_Sett3, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Btn_Sett3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Img_S3 = lv_img_create(ui_Home_Btn_Sett3);
    lv_img_set_src(ui_Home_Img_S3, &ui_img_home_icon_png);
    lv_obj_set_width(ui_Home_Img_S3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Img_S3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_Img_S3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Img_S3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home_Img_S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Home_Img_S3, 50);

    ui_PeekBooBTN = lv_btn_create(ui_Gamescr);
    lv_obj_set_width(ui_PeekBooBTN, 75);
    lv_obj_set_height(ui_PeekBooBTN, 68);
    lv_obj_set_x(ui_PeekBooBTN, 95);
    lv_obj_set_y(ui_PeekBooBTN, -59);
    lv_obj_set_align(ui_PeekBooBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PeekBooBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PeekBooBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PeekBooBTN, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PeekBooBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_PeekBooBTN);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "PB");

    ui_TetriBtn = lv_btn_create(ui_Gamescr);
    lv_obj_set_width(ui_TetriBtn, 75);
    lv_obj_set_height(ui_TetriBtn, 68);
    lv_obj_set_x(ui_TetriBtn, 8);
    lv_obj_set_y(ui_TetriBtn, -59);
    lv_obj_set_align(ui_TetriBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TetriBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TetriBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TetriBtn, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TetriBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_TetriBtn);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Tetris");

    ui_SnakeBtn = lv_btn_create(ui_Gamescr);
    lv_obj_set_width(ui_SnakeBtn, 75);
    lv_obj_set_height(ui_SnakeBtn, 68);
    lv_obj_set_x(ui_SnakeBtn, 9);
    lv_obj_set_y(ui_SnakeBtn, 36);
    lv_obj_set_align(ui_SnakeBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SnakeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SnakeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SnakeBtn, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnakeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_SnakeBtn);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Snake");

    lv_obj_add_event_cb(ui_Color_Btn_Home2, ui_event_Color_Btn_Home2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home_Btn_Sett3, ui_event_Home_Btn_Sett3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PeekBooBTN, ui_event_PeekBooBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TetriBtn, ui_event_TetriBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SnakeBtn, ui_event_SnakeBtn, LV_EVENT_ALL, NULL);

}

void ui_Gamescr_screen_destroy(void)
{
    if(ui_Gamescr) lv_obj_del(ui_Gamescr);

    // NULL screen variables
    ui_Gamescr = NULL;
    ui_Color_Btn_Home2 = NULL;
    ui_Colorwheel_Home2 = NULL;
    ui_Home_Btn_Sett3 = NULL;
    ui_Home_Img_S3 = NULL;
    ui_PeekBooBTN = NULL;
    ui_Label4 = NULL;
    ui_TetriBtn = NULL;
    ui_Label1 = NULL;
    ui_SnakeBtn = NULL;
    ui_Label2 = NULL;

}
