// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_InfoScr = NULL;
// event funtions

// build funtions

void ui_InfoScr_screen_init(void)
{
    ui_InfoScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InfoScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InfoScr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InfoScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_InfoScr_screen_destroy(void)
{
    if(ui_InfoScr) lv_obj_del(ui_InfoScr);

    // NULL screen variables
    ui_InfoScr = NULL;

}
