// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_PERSCREEN_H
#define UI_PERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PERscreen
extern void ui_PERscreen_screen_init(void);
extern void ui_PERscreen_screen_destroy(void);
extern lv_obj_t * ui_PERscreen;
extern void ui_event_Home_Btn_Sett2(lv_event_t * e);
extern lv_obj_t * ui_Home_Btn_Sett2;
extern lv_obj_t * ui_Home_Img_S2;
extern lv_obj_t * ui_uibtn1;
extern lv_obj_t * ui_uibtn2;
extern lv_obj_t * ui_uibtn3;
extern lv_obj_t * ui_uibtn4;
extern lv_obj_t * ui_Joyx;
extern lv_obj_t * ui_Joyy;
extern lv_obj_t * ui_Tempred;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

