// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_ppgscr = NULL;
lv_obj_t * ui_PlaybtnHB = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Home_Btn_Sett5 = NULL;
lv_obj_t * ui_Home_Img_S5 = NULL;
lv_obj_t * ui_PanelHB = NULL;
lv_obj_t * ui_BPM_label = NULL;
// event funtions
void ui_event_PlaybtnHB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pulseMeterStart(e);
    }
}

void ui_event_Home_Btn_Sett5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home_Scr, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Home_Scr_screen_init);
    }
}

// build funtions

void ui_ppgscr_screen_init(void)
{
    ui_ppgscr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ppgscr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ppgscr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ppgscr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlaybtnHB = lv_btn_create(ui_ppgscr);
    lv_obj_set_width(ui_PlaybtnHB, 75);
    lv_obj_set_height(ui_PlaybtnHB, 68);
    lv_obj_set_y(ui_PlaybtnHB, -68);
    lv_obj_set_x(ui_PlaybtnHB, lv_pct(-25));
    lv_obj_set_align(ui_PlaybtnHB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlaybtnHB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PlaybtnHB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PlaybtnHB, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlaybtnHB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_PlaybtnHB);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "play\n");

    ui_Home_Btn_Sett5 = lv_btn_create(ui_ppgscr);
    lv_obj_set_width(ui_Home_Btn_Sett5, 36);
    lv_obj_set_height(ui_Home_Btn_Sett5, 31);
    lv_obj_set_x(ui_Home_Btn_Sett5, -133);
    lv_obj_set_y(ui_Home_Btn_Sett5, 94);
    lv_obj_set_align(ui_Home_Btn_Sett5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Btn_Sett5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_Btn_Sett5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Btn_Sett5, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Btn_Sett5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Img_S5 = lv_img_create(ui_Home_Btn_Sett5);
    lv_img_set_src(ui_Home_Img_S5, &ui_img_home_icon_png);
    lv_obj_set_width(ui_Home_Img_S5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Img_S5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_Img_S5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Img_S5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home_Img_S5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Home_Img_S5, 50);

    ui_PanelHB = lv_obj_create(ui_ppgscr);
    lv_obj_set_width(ui_PanelHB, 100);
    lv_obj_set_height(ui_PanelHB, 50);
    lv_obj_set_x(ui_PanelHB, 54);
    lv_obj_set_y(ui_PanelHB, -5);
    lv_obj_set_align(ui_PanelHB, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BPM_label = lv_label_create(ui_PanelHB);
    lv_obj_set_width(ui_BPM_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BPM_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BPM_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BPM_label, "## BPM");

    lv_obj_add_event_cb(ui_PlaybtnHB, ui_event_PlaybtnHB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home_Btn_Sett5, ui_event_Home_Btn_Sett5, LV_EVENT_ALL, NULL);

}

void ui_ppgscr_screen_destroy(void)
{
    if(ui_ppgscr) lv_obj_del(ui_ppgscr);

    // NULL screen variables
    ui_ppgscr = NULL;
    ui_PlaybtnHB = NULL;
    ui_Label9 = NULL;
    ui_Home_Btn_Sett5 = NULL;
    ui_Home_Img_S5 = NULL;
    ui_PanelHB = NULL;
    ui_BPM_label = NULL;

}
