// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_PPGSCR_H
#define UI_PPGSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ppgscr
extern void ui_ppgscr_screen_init(void);
extern void ui_ppgscr_screen_destroy(void);
extern lv_obj_t * ui_ppgscr;
extern void ui_event_PlaybtnHB(lv_event_t * e);
extern lv_obj_t * ui_PlaybtnHB;
extern lv_obj_t * ui_Label9;
extern void ui_event_Home_Btn_Sett5(lv_event_t * e);
extern lv_obj_t * ui_Home_Btn_Sett5;
extern lv_obj_t * ui_Home_Img_S5;
extern lv_obj_t * ui_PanelHB;
extern lv_obj_t * ui_BPM_label;
extern lv_obj_t * ui_NaslPPG;
extern lv_obj_t * ui_Label17;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

