// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_PERscreen = NULL;
lv_obj_t * ui_Home_Btn_Sett2 = NULL;
lv_obj_t * ui_Home_Img_S2 = NULL;
lv_obj_t * ui_uibtn1 = NULL;
lv_obj_t * ui_uibtn2 = NULL;
lv_obj_t * ui_uibtn3 = NULL;
lv_obj_t * ui_uibtn4 = NULL;
lv_obj_t * ui_Joyx = NULL;
lv_obj_t * ui_Joyy = NULL;
lv_obj_t * ui_Tempred = NULL;
// event funtions
void ui_event_Home_Btn_Sett2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home_Scr, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Home_Scr_screen_init);
    }
}

// build funtions

void ui_PERscreen_screen_init(void)
{
    ui_PERscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PERscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PERscreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PERscreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Btn_Sett2 = lv_btn_create(ui_PERscreen);
    lv_obj_set_width(ui_Home_Btn_Sett2, 36);
    lv_obj_set_height(ui_Home_Btn_Sett2, 31);
    lv_obj_set_x(ui_Home_Btn_Sett2, -133);
    lv_obj_set_y(ui_Home_Btn_Sett2, 94);
    lv_obj_set_align(ui_Home_Btn_Sett2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Btn_Sett2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_Btn_Sett2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Btn_Sett2, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Btn_Sett2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Img_S2 = lv_img_create(ui_Home_Btn_Sett2);
    lv_img_set_src(ui_Home_Img_S2, &ui_img_home_icon_png);
    lv_obj_set_width(ui_Home_Img_S2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Img_S2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_Img_S2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Img_S2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home_Img_S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Home_Img_S2, 50);

    ui_uibtn1 = lv_label_create(ui_PERscreen);
    lv_obj_set_width(ui_uibtn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uibtn1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uibtn1, -100);
    lv_obj_set_y(ui_uibtn1, -81);
    lv_obj_set_align(ui_uibtn1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uibtn1, "BTN1 STATE");
    lv_obj_set_style_bg_color(ui_uibtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uibtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uibtn2 = lv_label_create(ui_PERscreen);
    lv_obj_set_width(ui_uibtn2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uibtn2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uibtn2, -97);
    lv_obj_set_y(ui_uibtn2, -53);
    lv_obj_set_align(ui_uibtn2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uibtn2, "BTN2 STATE");
    lv_obj_set_style_bg_color(ui_uibtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uibtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uibtn3 = lv_label_create(ui_PERscreen);
    lv_obj_set_width(ui_uibtn3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uibtn3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uibtn3, -97);
    lv_obj_set_y(ui_uibtn3, -23);
    lv_obj_set_align(ui_uibtn3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uibtn3, "BTN3 STATE");
    lv_obj_set_style_bg_color(ui_uibtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uibtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uibtn4 = lv_label_create(ui_PERscreen);
    lv_obj_set_width(ui_uibtn4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uibtn4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uibtn4, -96);
    lv_obj_set_y(ui_uibtn4, 8);
    lv_obj_set_align(ui_uibtn4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uibtn4, "BTN4 STATE");
    lv_obj_set_style_bg_color(ui_uibtn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uibtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Joyx = lv_label_create(ui_PERscreen);
    lv_obj_set_width(ui_Joyx, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Joyx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Joyx, 74);
    lv_obj_set_y(ui_Joyx, -83);
    lv_obj_set_align(ui_Joyx, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Joyx, "X - cor - ####");
    lv_obj_set_style_bg_color(ui_Joyx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Joyx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Joyy = lv_label_create(ui_PERscreen);
    lv_obj_set_width(ui_Joyy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Joyy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Joyy, 75);
    lv_obj_set_y(ui_Joyy, -52);
    lv_obj_set_align(ui_Joyy, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Joyy, "Y - cor - ####");
    lv_obj_set_style_bg_color(ui_Joyy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Joyy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tempred = lv_label_create(ui_PERscreen);
    lv_obj_set_width(ui_Tempred, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tempred, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Tempred, 75);
    lv_obj_set_y(ui_Tempred, -13);
    lv_obj_set_align(ui_Tempred, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Tempred, "Temp is ### C");
    lv_obj_set_style_bg_color(ui_Tempred, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tempred, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Home_Btn_Sett2, ui_event_Home_Btn_Sett2, LV_EVENT_ALL, NULL);

}

void ui_PERscreen_screen_destroy(void)
{
    if(ui_PERscreen) lv_obj_del(ui_PERscreen);

    // NULL screen variables
    ui_PERscreen = NULL;
    ui_Home_Btn_Sett2 = NULL;
    ui_Home_Img_S2 = NULL;
    ui_uibtn1 = NULL;
    ui_uibtn2 = NULL;
    ui_uibtn3 = NULL;
    ui_uibtn4 = NULL;
    ui_Joyx = NULL;
    ui_Joyy = NULL;
    ui_Tempred = NULL;

}
