// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_PHOTOSCR_H
#define UI_PHOTOSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_photoScr
extern void ui_photoScr_screen_init(void);
extern void ui_photoScr_screen_destroy(void);
extern lv_obj_t * ui_photoScr;
extern void ui_event_PlaybtnPhoto(lv_event_t * e);
extern lv_obj_t * ui_PlaybtnPhoto;
extern lv_obj_t * ui_Label1;
extern void ui_event_Home_Btn_Sett1(lv_event_t * e);
extern lv_obj_t * ui_Home_Btn_Sett1;
extern lv_obj_t * ui_Home_Img_S1;
extern lv_obj_t * ui_PanelHB1;
extern lv_obj_t * ui_BPM_label1;
extern lv_obj_t * ui_NaslPPG2;
extern lv_obj_t * ui_Label19;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

