// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_PEEKBOOSCR_H
#define UI_PEEKBOOSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PeekBooScr
extern void ui_PeekBooScr_screen_init(void);
extern void ui_PeekBooScr_screen_destroy(void);
extern lv_obj_t * ui_PeekBooScr;
extern void ui_event_Ret_Btn_Color2(lv_event_t * e);
extern lv_obj_t * ui_Ret_Btn_Color2;
extern lv_obj_t * ui_ret_Img_C2;
extern lv_obj_t * ui_Playbtng2;
extern lv_obj_t * ui_playbtnPB;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

