// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_photoScr = NULL;
lv_obj_t * ui_PlaybtnPhoto = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Home_Btn_Sett1 = NULL;
lv_obj_t * ui_Home_Img_S1 = NULL;
lv_obj_t * ui_PanelHB1 = NULL;
lv_obj_t * ui_BPM_label1 = NULL;
lv_obj_t * ui_NaslPPG2 = NULL;
lv_obj_t * ui_Label19 = NULL;
// event funtions
void ui_event_PlaybtnPhoto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        takePhoto(e);
    }
}

void ui_event_Home_Btn_Sett1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home_Scr, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Home_Scr_screen_init);
    }
}

// build funtions

void ui_photoScr_screen_init(void)
{
    ui_photoScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_photoScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_photoScr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_photoScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlaybtnPhoto = lv_btn_create(ui_photoScr);
    lv_obj_set_width(ui_PlaybtnPhoto, 75);
    lv_obj_set_height(ui_PlaybtnPhoto, 68);
    lv_obj_set_y(ui_PlaybtnPhoto, -7);
    lv_obj_set_x(ui_PlaybtnPhoto, lv_pct(-23));
    lv_obj_set_align(ui_PlaybtnPhoto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlaybtnPhoto, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PlaybtnPhoto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PlaybtnPhoto, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlaybtnPhoto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_PlaybtnPhoto);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "play\n");

    ui_Home_Btn_Sett1 = lv_btn_create(ui_photoScr);
    lv_obj_set_width(ui_Home_Btn_Sett1, 36);
    lv_obj_set_height(ui_Home_Btn_Sett1, 31);
    lv_obj_set_x(ui_Home_Btn_Sett1, -133);
    lv_obj_set_y(ui_Home_Btn_Sett1, 94);
    lv_obj_set_align(ui_Home_Btn_Sett1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Btn_Sett1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_Btn_Sett1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Btn_Sett1, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Btn_Sett1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Img_S1 = lv_img_create(ui_Home_Btn_Sett1);
    lv_img_set_src(ui_Home_Img_S1, &ui_img_home_icon_png);
    lv_obj_set_width(ui_Home_Img_S1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Img_S1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_Img_S1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Img_S1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home_Img_S1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Home_Img_S1, 50);

    ui_PanelHB1 = lv_obj_create(ui_photoScr);
    lv_obj_set_width(ui_PanelHB1, 100);
    lv_obj_set_height(ui_PanelHB1, 50);
    lv_obj_set_x(ui_PanelHB1, 54);
    lv_obj_set_y(ui_PanelHB1, -5);
    lv_obj_set_align(ui_PanelHB1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHB1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BPM_label1 = lv_label_create(ui_PanelHB1);
    lv_obj_set_width(ui_BPM_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BPM_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BPM_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BPM_label1, "nije u \nfunkciji");

    ui_NaslPPG2 = lv_obj_create(ui_photoScr);
    lv_obj_set_width(ui_NaslPPG2, 100);
    lv_obj_set_height(ui_NaslPPG2, 50);
    lv_obj_set_x(ui_NaslPPG2, -79);
    lv_obj_set_y(ui_NaslPPG2, -88);
    lv_obj_set_align(ui_NaslPPG2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NaslPPG2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NaslPPG2, lv_color_hex(0x52EA59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NaslPPG2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_NaslPPG2);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, -2);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Kamera");

    lv_obj_add_event_cb(ui_PlaybtnPhoto, ui_event_PlaybtnPhoto, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home_Btn_Sett1, ui_event_Home_Btn_Sett1, LV_EVENT_ALL, NULL);

}

void ui_photoScr_screen_destroy(void)
{
    if(ui_photoScr) lv_obj_del(ui_photoScr);

    // NULL screen variables
    ui_photoScr = NULL;
    ui_PlaybtnPhoto = NULL;
    ui_Label1 = NULL;
    ui_Home_Btn_Sett1 = NULL;
    ui_Home_Img_S1 = NULL;
    ui_PanelHB1 = NULL;
    ui_BPM_label1 = NULL;
    ui_NaslPPG2 = NULL;
    ui_Label19 = NULL;

}
