// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_PeekBooScr = NULL;
lv_obj_t * ui_Ret_Btn_Color2 = NULL;
lv_obj_t * ui_ret_Img_C2 = NULL;
lv_obj_t * ui_Playbtng2 = NULL;
lv_obj_t * ui_playbtnPB = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions
void ui_event_Ret_Btn_Color2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Gamescr, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Gamescr_screen_init);
    }
}

// build funtions

void ui_PeekBooScr_screen_init(void)
{
    ui_PeekBooScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PeekBooScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PeekBooScr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PeekBooScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ret_Btn_Color2 = lv_btn_create(ui_PeekBooScr);
    lv_obj_set_width(ui_Ret_Btn_Color2, 36);
    lv_obj_set_height(ui_Ret_Btn_Color2, 31);
    lv_obj_set_x(ui_Ret_Btn_Color2, -133);
    lv_obj_set_y(ui_Ret_Btn_Color2, 94);
    lv_obj_set_align(ui_Ret_Btn_Color2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Ret_Btn_Color2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Ret_Btn_Color2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ret_Btn_Color2, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ret_Btn_Color2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ret_Img_C2 = lv_img_create(ui_Ret_Btn_Color2);
    lv_img_set_src(ui_ret_Img_C2, &ui_img_1713359611);
    lv_obj_set_width(ui_ret_Img_C2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ret_Img_C2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ret_Img_C2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ret_Img_C2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ret_Img_C2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ret_Img_C2, 20);

    ui_Playbtng2 = lv_btn_create(ui_PeekBooScr);
    lv_obj_set_width(ui_Playbtng2, 75);
    lv_obj_set_height(ui_Playbtng2, 68);
    lv_obj_set_y(ui_Playbtng2, -54);
    lv_obj_set_x(ui_Playbtng2, lv_pct(-30));
    lv_obj_set_align(ui_Playbtng2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Playbtng2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Playbtng2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Playbtng2, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Playbtng2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playbtnPB = lv_img_create(ui_Playbtng2);
    lv_img_set_src(ui_playbtnPB, &ui_img_427326921);
    lv_obj_set_width(ui_playbtnPB, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_playbtnPB, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_playbtnPB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playbtnPB, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_playbtnPB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_playbtnPB, 48);
    lv_obj_set_style_bg_color(ui_playbtnPB, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playbtnPB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_PeekBooScr);
    lv_obj_set_width(ui_Panel4, 100);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_x(ui_Panel4, 60);
    lv_obj_set_y(ui_Panel4, -70);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x7D7D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Peek");

    ui_Panel1 = lv_obj_create(ui_PeekBooScr);
    lv_obj_set_width(ui_Panel1, 100);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, 60);
    lv_obj_set_y(ui_Panel1, -6);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x7D7D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "a");

    ui_Panel2 = lv_obj_create(ui_PeekBooScr);
    lv_obj_set_width(ui_Panel2, 100);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, 65);
    lv_obj_set_y(ui_Panel2, 62);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x7D7D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "boo");

    lv_obj_add_event_cb(ui_Ret_Btn_Color2, ui_event_Ret_Btn_Color2, LV_EVENT_ALL, NULL);

}

void ui_PeekBooScr_screen_destroy(void)
{
    if(ui_PeekBooScr) lv_obj_del(ui_PeekBooScr);

    // NULL screen variables
    ui_PeekBooScr = NULL;
    ui_Ret_Btn_Color2 = NULL;
    ui_ret_Img_C2 = NULL;
    ui_Playbtng2 = NULL;
    ui_playbtnPB = NULL;
    ui_Panel4 = NULL;
    ui_Label5 = NULL;
    ui_Panel1 = NULL;
    ui_Label6 = NULL;
    ui_Panel2 = NULL;
    ui_Label7 = NULL;

}
