// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_WIFISCR_H
#define UI_WIFISCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiScr
extern void ui_WifiScr_screen_init(void);
extern void ui_WifiScr_screen_destroy(void);
extern lv_obj_t * ui_WifiScr;
extern lv_obj_t * ui_Label15;
extern void ui_event_Home_Btn_Sett6(lv_event_t * e);
extern lv_obj_t * ui_Home_Btn_Sett6;
extern lv_obj_t * ui_Home_Img_S6;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label16;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

