// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_WifiScr = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Home_Btn_Sett6 = NULL;
lv_obj_t * ui_Home_Img_S6 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label16 = NULL;
// event funtions
void ui_event_Home_Btn_Sett6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home_Scr, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Home_Scr_screen_init);
    }
}

// build funtions

void ui_WifiScr_screen_init(void)
{
    ui_WifiScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WifiScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiScr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_WifiScr);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 3);
    lv_obj_set_y(ui_Label15, -5);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "NIJE U FUNKCIJI");
    lv_obj_set_style_bg_color(ui_Label15, lv_color_hex(0xFB6464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Btn_Sett6 = lv_btn_create(ui_WifiScr);
    lv_obj_set_width(ui_Home_Btn_Sett6, 36);
    lv_obj_set_height(ui_Home_Btn_Sett6, 31);
    lv_obj_set_x(ui_Home_Btn_Sett6, -133);
    lv_obj_set_y(ui_Home_Btn_Sett6, 94);
    lv_obj_set_align(ui_Home_Btn_Sett6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Btn_Sett6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_Btn_Sett6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Btn_Sett6, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Btn_Sett6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Img_S6 = lv_img_create(ui_Home_Btn_Sett6);
    lv_img_set_src(ui_Home_Img_S6, &ui_img_home_icon_png);
    lv_obj_set_width(ui_Home_Img_S6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Img_S6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_Img_S6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Img_S6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home_Img_S6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Home_Img_S6, 50);

    ui_Panel6 = lv_obj_create(ui_WifiScr);
    lv_obj_set_width(ui_Panel6, 100);
    lv_obj_set_height(ui_Panel6, 50);
    lv_obj_set_x(ui_Panel6, -86);
    lv_obj_set_y(ui_Panel6, -84);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "WIFI KLIJENT");

    lv_obj_add_event_cb(ui_Home_Btn_Sett6, ui_event_Home_Btn_Sett6, LV_EVENT_ALL, NULL);

}

void ui_WifiScr_screen_destroy(void)
{
    if(ui_WifiScr) lv_obj_del(ui_WifiScr);

    // NULL screen variables
    ui_WifiScr = NULL;
    ui_Label15 = NULL;
    ui_Home_Btn_Sett6 = NULL;
    ui_Home_Img_S6 = NULL;
    ui_Panel6 = NULL;
    ui_Label16 = NULL;

}
